name: Sync to Synology NAS

on:
  push:
    branches:
      - master # 'master' 브랜치에 푸시될 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git safe directory
        run: git config --global --add safe.directory /volume1/docker/node/nextjs-haru

      - name: Reset and clean working directory
        run: |
          git fetch origin
          git reset --hard origin/master
          git clean -fd

      - name: Sync with Synology NAS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EXTERNAL_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222 # 외부에서 접속할 포트
          script: |
            git config --global --add safe.directory /volume1/docker/node/nextjs-haru
            cd /volume1/docker/node/nextjs-haru
            git pull origin master
